run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - revive
    - bodyclose

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: blank-imports
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning
      - name: error-naming
        severity: warning
      - name: if-return
        severity: warning
      - name: var-naming
        severity: warning
      - name: receiver-naming
        severity: warning

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
